// <auto-generated />
using FEDPAYmgr.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace FEDPAY.Migrations
{
    [DbContext(typeof(FEDPAYContext))]
    [Migration("20181121182759_addNMC")]
    partial class addNMC
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fedpay")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("FEDPAY.Models.Non_Merchandise_Code", b =>
                {
                    b.Property<string>("NMC_CODE")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2);

                    b.Property<string>("NMC_ADJUSTMENT_IND")
                        .HasMaxLength(1);

                    b.Property<string>("NMC_ADMIN_DIFF_IND")
                        .HasMaxLength(1);

                    b.Property<string>("NMC_BILLING_LIT")
                        .HasMaxLength(15);

                    b.Property<string>("NMC_INVOICE_ACTION")
                        .HasMaxLength(1);

                    b.Property<string>("NMC_MEANING")
                        .HasMaxLength(40);

                    b.Property<string>("NMC_PO_TD_CODE")
                        .HasMaxLength(2);

                    b.Property<string>("NMC_SYS_CODE")
                        .HasMaxLength(1);

                    b.Property<string>("NMC_TRANSACTION_ID")
                        .HasMaxLength(4);

                    b.HasKey("NMC_CODE");

                    b.ToTable("Non_Merchandise_Code");
                });

            modelBuilder.Entity("FEDPAY.Models.Region", b =>
                {
                    b.Property<string>("REG_PO_SUFFIX")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("REG_FAIM_FB_REGION_CODE");

                    b.Property<string>("REG_FEDPAY_REGION_CODE");

                    b.Property<string>("REG_FSS_REGION_CODE");

                    b.Property<string>("REG_INFONET_REGION_CODE");

                    b.Property<string>("REG_ROUTING_ID");

                    b.HasKey("REG_PO_SUFFIX");

                    b.ToTable("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
