// <auto-generated />
using System;
using FEDPAYmgr.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace FEDPAY.Migrations
{
    [DbContext(typeof(FEDPAYContext))]
    partial class FEDPAYContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fedpay")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("FEDPAY.Models.Admin_Diff", b =>
                {
                    b.Property<string>("ADD_PO_NO");

                    b.Property<string>("ADD_INVOICE_NO");

                    b.Property<int>("ADD_SEQ_NO")
                        .HasMaxLength(6);

                    b.Property<decimal>("ADD_AMT");

                    b.Property<int?>("ADD_BILLED_QTY");

                    b.Property<decimal?>("ADD_BILLED_UCP");

                    b.Property<string>("ADD_CLAIM_CONTROL_NO")
                        .HasMaxLength(8);

                    b.Property<DateTime>("ADD_DATE_OF_DIFF");

                    b.Property<string>("ADD_ERROR_CD")
                        .HasMaxLength(6);

                    b.Property<string>("ADD_FSS_PO_NO")
                        .HasMaxLength(11);

                    b.Property<string>("ADD_INITIALS")
                        .HasMaxLength(3);

                    b.Property<string>("ADD_NON_MERCH_CODE")
                        .HasMaxLength(2);

                    b.Property<int?>("ADD_PO_QTY");

                    b.Property<decimal?>("ADD_PO_UCP");

                    b.Property<string>("ADD_STOCK_NO")
                        .HasMaxLength(15);

                    b.Property<string>("ADD_VENDOR_NO")
                        .HasMaxLength(9);

                    b.HasKey("ADD_PO_NO", "ADD_INVOICE_NO", "ADD_SEQ_NO");

                    b.ToTable("Admin_Diff");
                });

            modelBuilder.Entity("FEDPAY.Models.Fedpay_Err_Mes", b =>
                {
                    b.Property<string>("FEM_ERR_CODE")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(6);

                    b.Property<string>("FEM_AD_IRN_CODE")
                        .HasMaxLength(2);

                    b.Property<string>("FEM_FORM_MESSAGE")
                        .HasMaxLength(120);

                    b.Property<string>("FEM_IRN_CODE")
                        .HasMaxLength(2);

                    b.Property<string>("FEM_NMC")
                        .HasMaxLength(2);

                    b.Property<string>("FEM_SYS_CODE")
                        .HasMaxLength(2);

                    b.HasKey("FEM_ERR_CODE");

                    b.ToTable("Fedpay_Err_MES");
                });

            modelBuilder.Entity("FEDPAY.Models.Invoice_Summary", b =>
                {
                    b.Property<string>("INS_PO_NO")
                        .HasMaxLength(9);

                    b.Property<string>("INS_INVOICE_NO")
                        .HasMaxLength(12);

                    b.Property<decimal>("INS_ADMIN_DIFF_AMT");

                    b.Property<decimal>("INS_AMT_PAID");

                    b.Property<decimal>("INS_INVOICE_AMT");

                    b.Property<string>("INS_VENDOR_NO")
                        .HasMaxLength(12);

                    b.HasKey("INS_PO_NO", "INS_INVOICE_NO");

                    b.ToTable("Invoice_Summary");
                });

            modelBuilder.Entity("FEDPAY.Models.Non_Merchandise_Code", b =>
                {
                    b.Property<string>("NMC_CODE")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2);

                    b.Property<string>("NMC_ADJUSTMENT_IND")
                        .HasMaxLength(1);

                    b.Property<string>("NMC_ADMIN_DIFF_IND")
                        .HasMaxLength(1);

                    b.Property<string>("NMC_BILLING_LIT")
                        .HasMaxLength(15);

                    b.Property<string>("NMC_INVOICE_ACTION")
                        .HasMaxLength(1);

                    b.Property<string>("NMC_MEANING")
                        .HasMaxLength(40);

                    b.Property<string>("NMC_PO_TD_CODE")
                        .HasMaxLength(2);

                    b.Property<string>("NMC_SYS_CODE")
                        .HasMaxLength(1);

                    b.Property<string>("NMC_TRANSACTION_ID")
                        .HasMaxLength(4);

                    b.HasKey("NMC_CODE");

                    b.ToTable("Non_Merchandise_Code");
                });

            modelBuilder.Entity("FEDPAY.Models.Region", b =>
                {
                    b.Property<string>("REG_PO_SUFFIX")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("REG_FAIM_FB_REGION_CODE");

                    b.Property<string>("REG_FEDPAY_REGION_CODE");

                    b.Property<string>("REG_FSS_REGION_CODE");

                    b.Property<string>("REG_INFONET_REGION_CODE");

                    b.Property<string>("REG_ROUTING_ID");

                    b.HasKey("REG_PO_SUFFIX");

                    b.ToTable("Region");
                });

            modelBuilder.Entity("FEDPAY.Models.Vendor", b =>
                {
                    b.Property<string>("VEN_VENDOR_NO")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(9);

                    b.Property<string>("VEN_ADDRESS1")
                        .HasMaxLength(35);

                    b.Property<string>("VEN_ADDRESS2")
                        .HasMaxLength(35);

                    b.Property<string>("VEN_ADDRESS3")
                        .HasMaxLength(35);

                    b.Property<string>("VEN_CITY_NAME")
                        .HasMaxLength(20);

                    b.Property<string>("VEN_NAME")
                        .HasMaxLength(35);

                    b.Property<string>("VEN_STATE_ABBR")
                        .HasMaxLength(2);

                    b.Property<string>("VEN_ZIP_CODE")
                        .HasMaxLength(5);

                    b.Property<string>("ven_vendor_alt_key")
                        .HasMaxLength(30);

                    b.HasKey("VEN_VENDOR_NO");

                    b.ToTable("Vendor");
                });

            modelBuilder.Entity("FEDPAY.Models.Admin_Diff", b =>
                {
                    b.HasOne("FEDPAY.Models.Invoice_Summary", "Invoice_Summary")
                        .WithMany("Admin_Diffs")
                        .HasForeignKey("ADD_PO_NO", "ADD_INVOICE_NO")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
